### ISSUE TITLE
IT Tests don't clean up the namespaces

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#395]
We have right now multiple stale namespaces in our zeebe-cluster:

```
$ kubens
camunda-platform-9xrwyd-73d6b02d6ca53856b57895814f096056ee33d03
camunda-platform-ahuw7m-144d44e8bdf7ac6a05b1e962cbec5177e970a64
camunda-platform-hh011d-95ee9a52901d52ebbd98f7d9f5687d2eb88bfed
camunda-platform-ls55t3-1559d34127e3d94afe7aab68dcc70bfb76a1ae2
camunda-platform-n9xyai-95ee9a52901d52ebbd98f7d9f5687d2eb88bfed
camunda-platform-sveg0d-94856d10a4eedfc9e35456c16efdd92c0fa40ee
camunda-platform-txs9sh-95ee9a52901d52ebbd98f7d9f5687d2eb88bfed
```

Which haven't been deleted. 

This can happen in certain conditions, which everyone needs to be aware of.

1. when an integration test fails, we do not delete the namespace since we might want to find out what went wrong
2. when a github action was canceled this might cause as well that the resources are not cleaned up

I just wanted to raise this topic and make you aware @aabouzaid. We might need to think whether we want to keep it like that, that we have to clean up manually or we find a better way.

**Comment by Zelldon** [comment]
It is getting worse. I have to clean them up manually from time to time, but if I don't do we end up with like:

```
camunda-platform-pr-482-sha-1459d13-run-3437565679-rnd-23sldp
camunda-platform-pr-482-sha-1459d13-run-3437565679-rnd-binrtg
camunda-platform-pr-482-sha-1459d13-run-3437565679-rnd-evfbyf
camunda-platform-pr-482-sha-1459d13-run-3437565679-rnd-gmzczg
camunda-platform-pr-482-sha-1459d13-run-3437565679-rnd-imhrqg
camunda-platform-pr-482-sha-1459d13-run-3437565679-rnd-ldgifk
camunda-platform-pr-482-sha-f544f1c-run-3438242286-rnd-124thy
camunda-platform-pr-482-sha-f544f1c-run-3438242286-rnd-l8d7vn
camunda-platform-pr-484-sha-30fd066-run-3461859311-rnd-0u8pqj
camunda-platform-pr-484-sha-30fd066-run-3461859311-rnd-9juauu
camunda-platform-pr-484-sha-30fd066-run-3461859311-rnd-niwl1d
camunda-platform-pr-484-sha-30fd066-run-3461859311-rnd-opm0lr
camunda-platform-pr-484-sha-918f303-run-3461509014-rnd-aqqum2
camunda-platform-pr-484-sha-918f303-run-3461509014-rnd-wg3sg0
camunda-platform-pr-485-sha-00f3ca7-run-3462733242-rnd-c4lxzy
camunda-platform-pr-485-sha-00f3ca7-run-3462733242-rnd-clwj8r
camunda-platform-pr-487-sha-60e5b39-run-3471397672-rnd-6bedn5
camunda-platform-pr-487-sha-73546a5-run-3469220915-rnd-ge0uyd
camunda-platform-pr-487-sha-73546a5-run-3469220915-rnd-plxs3a
camunda-platform-pr-487-sha-73546a5-run-3469220915-rnd-xmbvjx
camunda-platform-pr-487-sha-aa8538c-run-3469540626-rnd-m2icb3
camunda-platform-pr-487-sha-c89e6ac-run-3472006854-rnd-vwgi4e
camunda-platform-pr-487-sha-ee8bdb5-run-3469241907-rnd-w1ndrq
camunda-platform-pr-487-sha-f4872c5-run-3472005051-rnd-2trhue
```

```
$ k get pods --namespace camunda-platform-pr-487-sha-73546a5-run-3469220915-rnd-ge0uyd | grep camunda-platform | wc -l
16
```
It seems that they also have resources deployed..

```
$ k get pods --namespace camunda-platform-pr-487-sha-73546a5-run-3469220915-rnd-ge0uyd
NAME                                                 READY   STATUS    RESTARTS   AGE
camunda-platform-it-0                                1/1     Running   0          21h
camunda-platform-it-identity-5f5dbd9dc8-rj9g5        1/1     Running   0          89m
camunda-platform-it-identity-5f5dbd9dc8-tlc56        0/1     Error     0          44h
camunda-platform-it-operate-5f699bdf7f-2vzg8         1/1     Running   0          20h
camunda-platform-it-optimize-8f549f548-5qtpj         1/1     Running   0          21h
camunda-platform-it-optimize-8f549f548-xxhhb         0/1     Error     0          44h
camunda-platform-it-postgresql-0                     1/1     Running   0          21h
camunda-platform-it-tasklist-5f48796bf-fmxsf         1/1     Running   0          21h
camunda-platform-it-tasklist-5f48796bf-fqqtf         0/1     Error     0          44h
camunda-platform-it-zeebe-0                          1/1     Running   0          9h
camunda-platform-it-zeebe-1                          1/1     Running   0          21h
camunda-platform-it-zeebe-2                          1/1     Running   0          21h
camunda-platform-it-zeebe-gateway-7795cb99fd-fgktn   1/1     Running   0          8h
camunda-platform-it-zeebe-gateway-7795cb99fd-ngn2j   1/1     Running   0          21h
camunda-platform-it-zeebe-gateway-7795cb99fd-xmltj   0/1     Error     0          14h
camunda-platform-it-zeebe-gateway-7795cb99fd-xvd5b   0/1     Error     0          44h
elasticsearch-master-0                               1/1     Running   0          16h
elasticsearch-master-1                               1/1     Running   0          21h
```

This impacts our benchmarks and of course also costs.
I think we should fix that @megglos @npepinpe or we agree that everyone cleans it up from time to time (which is probably the easiest but not optimal solution).

I guess we could also create a separate cluster for @aabouzaid and the integration tests.

P.S:

I use:

```
function cleanNamespaces() {
  if [ -z "$1" ]
  then
    echo "Please provide a namespace prefix, like zell-"
    return 1
  fi

  prefix=$1
  kubectl get namespaces | grep "$prefix" | awk '{ print $1 }' | xargs -L1 kubectl delete namespace --wait=false
}
```

**Comment by aabouzaid** [comment]
@Zelldon I also do that and clean them manually, so the situation is even worse :D
The good news is that next week I will work on GKE support and I will create a cluster for distro team.
And in the new cluster, I will set up a corn to clean any namespace older than x days.

**Comment by aabouzaid** [comment]
In the end, I've found it's better to enhance the logs and delete the namespace by default unless the owner finds a persistent error and wants to debug it.

I've implemented a retry that supports backoff to not hammer the logs without much value (it's a limitation on the terratest side).

That will save costs and enhance debugging.

**Comment by Zelldon** [comment]
Thanks @aabouzaid for working on this :+1: 

I was just wondering why we still have some of these namespace in the zeebe-cluster:

```
$ kubens
78095a4a-fad3-45f7-99f1-50a686a567c6
camunda-platform-pr-500-sha-4d32afd-run-3584321380-rnd-rccpdc
camunda-platform-pr-500-sha-fc12626-run-3584376876-rnd-pgztab
camunda-platform-pr-500-sha-fc12626-run-3584376876-rnd-wbss4e
camunda-platform-pr-501-sha-039ba16-run-3585145618-rnd-5nlbch
camunda-platform-pr-501-sha-039ba16-run-3585145618-rnd-6bv2sr
camunda-platform-pr-501-sha-039ba16-run-3585145618-rnd-rsnklu
camunda-platform-pr-501-sha-039ba16-run-3585145618-rnd-swolv6
camunda-platform-pr-501-sha-039ba16-run-3585145618-rnd-t9x6so
camunda-platform-pr-501-sha-039ba16-run-3585145618-rnd-tdigny
camunda-platform-pr-501-sha-039ba16-run-3585145618-rnd-ttxi6b
cc31a207-841a-49a4-b859-c3a48669e461
```

Do you know?

**Comment by Zelldon** [comment]
Thanks @aabouzaid makes sense👍
